name: Scrape and Upload to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # daily at 2AM UTC

permissions:
  contents: write  # ← Required to allow pushes from actions

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: python -m playwright install

      - name: Run scraper
        run: python scraper_fique.py

      - name: Upload to Azure Blob Storage
        run: python upload_blob.py
        env:
          AZURE_CONN_STR: ${{ secrets.AZURE_CONN_STR }}

      - name: Make push script executable
        run: chmod +x push_jsonl.sh

      - name: Push updated JSONL to GitHub
        run: ./push_jsonl.sh
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
